module.exports.exercises = [
  "Abductor Machine",
  "Aduction Machine",
  "Arnold Press",
  "Barbell Bicep Curl",
  "Barbell Preacher Curl",
  "Barbell Shrug",
  "Barbell Skullcrusher",
  "Bench Press",
  "Bent Over Row",
  "Cable Bicep Curl",
  "Cable Pulldown",
  "Cable Row",
  "Calf Raise Machine",
  "Close Grip Bench Press",
  "Concentration Curl",
  "Deadlift - Conventional",
  "Deadlift - Sumo",
  "Deadlift - Trap Bar",
  "Dips",
  "Dumbbell Bench Press",
  "Dumbbell Bicep Curls",
  "Dumbbell Chest Fly",
  "Dumbbell Chest Pullovers",
  "Dumbbell Front Raise",
  "Dumbbell Hammer Curl",
  "Dumbbell Incline Bench",
  "Dumbbell Lateral Raise",
  "Dumbbell Reverse Fly",
  "Dumbbell Shoulder Press",
  "Dumbbell Shrug",
  "Face Pull",
  "Hack Squat",
  "Hamstring Curl Machine",
  "Incline Bench Press",
  "Incline Dumbbell Curl",
  "Include Bench Press Machine",
  "Inverted Leg Press Machine",
  "Landmine Press",
  "Lat Pulldown",
  "Leg Extension Machine",
  "Leg Press Machine",
  "Machine Chest Press",
  "Machine Row",
  "Machine Shoulder Press",
  "Military Press",
  "One Arm Cable Row",
  "One Arm Dumbbell Preacher Curl",
  "One Arm Dumbbell Row",
  "One Arm Tricep Extension",
  "Pec Fly Machine",
  "Preacher Curl Machine",
  "Rack Pull",
  "Reverse Barbell Curl",
  "Server Dumbbell Curl",
  "Shoulder Pin Press",
  "Squat",
  "T Bar Row",
  "Triceps Cable Pushdown",
  "Triceps Extension Machine",
  "Two Arm Tricep Extension",
  "Upright Row"
];
